import {
  ABS,
  BICEPS,
  CALVES,
  CHEST,
  GLUTES,
  HAMSTRINGS,
  HIP,
  INNER_THIGH,
  LOWER_BACK,
  NECK,
  OBLIQUES,
  QUADS,
  SHOULDERS,
  TRICEPS,
  WINGS,
} from "./areas";

export const BODY_WEIGHT = "body weight";
export const bodyWeight = [
  {
    id: "1",
    category: BODY_WEIGHT,
    name: "push-up",
    areas: [CHEST, SHOULDERS, TRICEPS, ABS, WINGS],
  },
  {
    id: "2",
    category: BODY_WEIGHT,
    name: "pull-up",
    areas: [CHEST, SHOULDERS, BICEPS, TRICEPS, LOWER_BACK, WINGS],
  },
  {
    id: "3",
    category: BODY_WEIGHT,
    name: "squat",
    areas: [GLUTES, QUADS, HAMSTRINGS, INNER_THIGH, CALVES, HIP],
  },
  {
    id: "4",
    category: BODY_WEIGHT,
    name: "sit-up",
    areas: [ABS, OBLIQUES, HIP, CHEST, NECK],
  },
  {
    id: "5",
    category: BODY_WEIGHT,
    name: "dip",
    areas: [CHEST, SHOULDERS, TRICEPS],
  },
  {
    id: "6",
    category: BODY_WEIGHT,
    name: "side sit-up",
    areas: [ABS, OBLIQUES, WINGS, CHEST, NECK],
  },
  {
    id: "7",
    category: BODY_WEIGHT,
    name: "plank",
    areas: [ABS, OBLIQUES, LOWER_BACK, SHOULDERS],
  },
  {
    id: "8",
    category: BODY_WEIGHT,
    name: "side plank",
    areas: [ABS, OBLIQUES, WINGS, LOWER_BACK, SHOULDERS, TRICEPS],
  },
  {
    id: "9",
    category: BODY_WEIGHT,
    name: "lunge",
    areas: [GLUTES, QUADS, HAMSTRINGS, CALVES, HIP],
  },
  {
    id: "10",
    category: BODY_WEIGHT,
    name: "burpee",
    areas: [
      CHEST,
      TRICEPS,
      SHOULDERS,
      GLUTES,
      QUADS,
      CALVES,
      HIP,
      ABS,
      OBLIQUES,
      LOWER_BACK,
    ],
  },
  {
    id: "11",
    category: BODY_WEIGHT,
    name: "glute bridge",
    areas: [GLUTES, ABS, HAMSTRINGS],
  },
  { id: "12", category: BODY_WEIGHT, name: "swiss ball rollout" },
  {
    id: "13",
    category: BODY_WEIGHT,
    name: "the bird dog aka one-arm, one-leg plank",
  },
  {
    id: "14",
    category: BODY_WEIGHT,
    name: "diamond push-up",
    areas: [CHEST, SHOULDERS, TRICEPS, ABS, WINGS],
  },
  {
    id: "15",
    category: BODY_WEIGHT,
    name: "BOSU ball push-up",
    areas: [CHEST, SHOULDERS, TRICEPS, ABS, WINGS],
  },
  {
    id: "16",
    category: BODY_WEIGHT,
    name: "punchers push-up",
    areas: [CHEST, SHOULDERS, TRICEPS, ABS, WINGS],
  },
  {
    id: "17",
    category: BODY_WEIGHT,
    name: "TRX suspended push-up",
    areas: [CHEST, SHOULDERS, TRICEPS, ABS, WINGS],
  },
  {
    id: "18",
    category: BODY_WEIGHT,
    name: "bulgarian split squat",
  },
  {
    id: "19",
    category: BODY_WEIGHT,
    name: "calf raise",
  },
  {
    id: "20",
    category: BODY_WEIGHT,
    name: "barbell ab rollout",
  },
  {
    id: "21",
    category: BODY_WEIGHT,
    name: "jackknife situp",
  },
  {
    id: "22",
    category: BODY_WEIGHT,
    name: "chin-up",
    areas: [CHEST, SHOULDERS, BICEPS, TRICEPS, LOWER_BACK, WINGS],
  },
];
