export const FREE_WEIGHT = "free weight";

export const freeWeight = [
  { id: "101", category: FREE_WEIGHT, name: "barbell bicep curl" },
  { id: "102", category: FREE_WEIGHT, name: "barbell bench press" },
  { id: "103", category: FREE_WEIGHT, name: "barbell incline bench press" },
  { id: "104", category: FREE_WEIGHT, name: "barbell decline bench press" },
  {
    id: "105",
    category: FREE_WEIGHT,
    name: "dumbbell standing overhead press",
  },
  { id: "106", category: FREE_WEIGHT, name: "dumbbell row" },
  { id: "107", category: FREE_WEIGHT, name: "single-leg deadlift" },
  { id: "108", category: FREE_WEIGHT, name: "barbell deadlift" },
  { id: "109", category: FREE_WEIGHT, name: "barbell back squat" },
  { id: "110", category: FREE_WEIGHT, name: "dumbbell romanian deadlift" },
  { id: "111", category: FREE_WEIGHT, name: "kettlebell swing" },
  { id: "112", category: FREE_WEIGHT, name: "medicine ball slam" },
  { id: "113", category: FREE_WEIGHT, name: "t-bar row" },
  { id: "115", category: FREE_WEIGHT, name: "farmers walk" },
  { id: "116", category: FREE_WEIGHT, name: "standing barbell bicep curl" },
  { id: "117", category: FREE_WEIGHT, name: "shrug" },
  { id: "119", category: FREE_WEIGHT, name: "dumbbell lateral raise" },
  { id: "120", category: FREE_WEIGHT, name: "overhead barbell press" },
  { id: "121", category: FREE_WEIGHT, name: "rear delt raises" },
  { id: "122", category: FREE_WEIGHT, name: "half-kneeling landmine press" },
  { id: "123", category: FREE_WEIGHT, name: "dumbbell bicep curl" },
  { id: "124", category: FREE_WEIGHT, name: "dumbbell bench press" },
  { id: "125", category: FREE_WEIGHT, name: "dumbbell incline bench press" },
  {
    id: "126",
    category: FREE_WEIGHT,
    name: "dumbbell decline bench press",
  },
  {
    id: "127",
    category: FREE_WEIGHT,
    name: "incline flye",
  },
  {
    id: "128",
    category: FREE_WEIGHT,
    name: "calf raise",
  },
  {
    id: "129",
    category: FREE_WEIGHT,
    name: "weighted decline situp",
  },
  {
    id: "130",
    category: FREE_WEIGHT,
    name: "dumbbell incline flye",
  },
  {
    id: "131",
    category: FREE_WEIGHT,
    name: "dumbbell tricep extension",
  },
  {
    id: "132",
    category: FREE_WEIGHT,
    name: "bent-over row",
  },
  { id: "133", category: FREE_WEIGHT, name: "dumbbell incline bicep curl" },
  { id: "134", category: FREE_WEIGHT, name: "good morning" },
  { id: "135", category: FREE_WEIGHT, name: "weighted hip thrust" },
  { id: "136", category: FREE_WEIGHT, name: "rack pull" },
  { id: "137", category: FREE_WEIGHT, name: "lateral raise" },
  { id: "138", category: FREE_WEIGHT, name: "reverse flye" },
  { id: "139", category: FREE_WEIGHT, name: "dumbbell one-arm row" },
];
