import {
  ABS,
  BICEPS,
  TRICEPS,
  CALVES,
  PECS,
  GLUTES,
  HAMSTRINGS,
  HIP,
  INNER_THIGH,
  OBLIQUES,
  QUADS,
  DELTS,
  UPPER_TRAPS,
  LOWER_TRAPS,
  SPINAL_ERECTOR,
  LATS,
  UPPER_PECS,
  LOWER_PECS,
} from "./areas";

export const FREE_WEIGHT = "free weight";

export const freeWeight = [
  {
    id: "101",
    category: FREE_WEIGHT,
    name: "barbell bicep curl",
    areas: [BICEPS],
  },
  {
    id: "102",
    category: FREE_WEIGHT,
    name: "barbell bench press",
    areas: [PECS, TRICEPS],
  },
  {
    id: "103",
    category: FREE_WEIGHT,
    name: "barbell incline bench press",
    areas: [UPPER_PECS, TRICEPS],
  },
  {
    id: "104",
    category: FREE_WEIGHT,
    name: "barbell decline bench press",
    areas: [LOWER_PECS, TRICEPS],
  },
  {
    id: "105",
    category: FREE_WEIGHT,
    name: "dumbbell standing overhead press",
    areas: [DELTS, UPPER_PECS, TRICEPS, UPPER_TRAPS, LOWER_TRAPS],
  },
  {
    id: "106",
    category: FREE_WEIGHT,
    name: "dumbbell row",
    areas: [LATS, DELTS, TRICEPS, LOWER_TRAPS],
  },
  {
    id: "107",
    category: FREE_WEIGHT,
    name: "single-leg deadlift",
    areas: [GLUTES, HAMSTRINGS, SPINAL_ERECTOR, ABS, OBLIQUES],
  },
  {
    id: "108",
    category: FREE_WEIGHT,
    name: "barbell deadlift",
    areas: [SPINAL_ERECTOR, GLUTES, QUADS, HAMSTRINGS, LOWER_TRAPS, LATS],
  },
  {
    id: "109",
    category: FREE_WEIGHT,
    name: "barbell back squat",
    areas: [SPINAL_ERECTOR, GLUTES, HAMSTRINGS, LATS],
  },
  {
    id: "110",
    category: FREE_WEIGHT,
    name: "dumbbell romanian deadlift",
    areas: [],
  },
  { id: "111", category: FREE_WEIGHT, name: "kettlebell swing", areas: [] },
  { id: "112", category: FREE_WEIGHT, name: "medicine ball slam", areas: [] },
  { id: "113", category: FREE_WEIGHT, name: "t-bar row", areas: [] },
  { id: "115", category: FREE_WEIGHT, name: "farmers walk", areas: [] },
  {
    id: "116",
    category: FREE_WEIGHT,
    name: "standing barbell bicep curl",
    areas: [],
  },
  { id: "117", category: FREE_WEIGHT, name: "shrug", areas: [] },
  {
    id: "119",
    category: FREE_WEIGHT,
    name: "dumbbell lateral raise",
    areas: [],
  },
  {
    id: "120",
    category: FREE_WEIGHT,
    name: "overhead barbell press",
    areas: [],
  },
  { id: "121", category: FREE_WEIGHT, name: "rear delt raises", areas: [] },
  {
    id: "122",
    category: FREE_WEIGHT,
    name: "half-kneeling landmine press",
    areas: [],
  },
  { id: "123", category: FREE_WEIGHT, name: "dumbbell bicep curl", areas: [] },
  { id: "124", category: FREE_WEIGHT, name: "dumbbell bench press", areas: [] },
  {
    id: "125",
    category: FREE_WEIGHT,
    name: "dumbbell incline bench press",
    areas: [],
  },
  {
    id: "126",
    category: FREE_WEIGHT,
    name: "dumbbell decline bench press",
    areas: [],
  },
  {
    id: "127",
    category: FREE_WEIGHT,
    name: "incline flye",
    areas: [],
  },
  {
    id: "128",
    category: FREE_WEIGHT,
    name: "calf raise",
    areas: [],
  },
  {
    id: "129",
    category: FREE_WEIGHT,
    name: "weighted decline situp",
    areas: [],
  },
  {
    id: "130",
    category: FREE_WEIGHT,
    name: "dumbbell incline flye",
    areas: [],
  },
  {
    id: "131",
    category: FREE_WEIGHT,
    name: "dumbbell tricep extension",
    areas: [],
  },
  {
    id: "132",
    category: FREE_WEIGHT,
    name: "bent-over row",
    areas: [],
  },
  {
    id: "133",
    category: FREE_WEIGHT,
    name: "dumbbell incline bicep curl",
    areas: [],
  },
  { id: "134", category: FREE_WEIGHT, name: "good morning", areas: [] },
  { id: "135", category: FREE_WEIGHT, name: "weighted hip thrust", areas: [] },
  { id: "136", category: FREE_WEIGHT, name: "rack pull", areas: [] },
  { id: "137", category: FREE_WEIGHT, name: "lateral raise", areas: [] },
  { id: "138", category: FREE_WEIGHT, name: "reverse flye", areas: [] },
  { id: "139", category: FREE_WEIGHT, name: "dumbbell one-arm row", areas: [] },
];
