import {
  BICEPS,
  CALVES,
  GLUTES,
  HAMSTRINGS,
  QUADS,
  HIP,
  INNER_THIGH,
  PECS,
  DELTS,
  TRICEPS,
  LOWER_PECS,
  UPPER_TRAPS,
  RHOMBOIDS,
  ABS,
  OBLIQUES,
  FOREARMS,
  LATS,
} from "./areas";

export const MACHINE = "machine";

export const machine = [
  {
    id: "201",
    category: MACHINE,
    name: "bicep curl",
    unit: "kg",
    areas: [BICEPS],
  },
  {
    id: "202",
    category: MACHINE,
    name: "squat",
    unit: "kg",
    areas: [GLUTES, QUADS, HAMSTRINGS, INNER_THIGH, HIP, CALVES],
  },
  {
    id: "203",
    category: MACHINE,
    name: "bench press",
    unit: "kg",
    areas: [PECS, DELTS, TRICEPS],
  },
  {
    id: "204",
    category: MACHINE,
    name: "cable crossover",
    unit: "kg",
    areas: [LOWER_PECS, DELTS, UPPER_TRAPS, RHOMBOIDS],
  },
  {
    id: "205",
    category: MACHINE,
    name: "lat pulldown 30 degree",
    unit: "kg",
    areas: [DELTS, BICEPS, FOREARMS],
  },
  {
    id: "206",
    category: MACHINE,
    name: "leg curl",
    unit: "kg",
    areas: [HAMSTRINGS, CALVES],
  },
  {
    id: "207",
    category: MACHINE,
    name: "leg extension",
    unit: "kg",
    areas: [QUADS],
  },
  {
    id: "208",
    category: MACHINE,
    name: "calf raise",
    unit: "kg",
    areas: [CALVES],
  },
  {
    id: "209",
    category: MACHINE,
    name: "cable woodchop",
    unit: "kg",
    areas: [ABS, OBLIQUES],
  },
  {
    id: "210",
    category: MACHINE,
    name: "lat pulldown",
    unit: "kg",
    areas: [LATS, DELTS],
  },
];
