import {
  CALVES,
  GLUTES,
  HAMSTRINGS,
  HIP,
  SPINAL_ERECTOR,
  OBLIQUES,
  QUADS,
  LOWER_TRAPS,
  FOREARMS,
  INNER_THIGH,
  OUTER_THIGH,
  LATS,
  PECS,
  DELTS,
  ABS,
} from "./areas";

export const MOBILITY = "mobility";
export const mobility = [
  {
    id: "301",
    category: MOBILITY,
    name: "toe touches",
    unit: "reps",
    areas: [HAMSTRINGS, CALVES, SPINAL_ERECTOR, LOWER_TRAPS],
  },
  {
    id: "302",
    category: MOBILITY,
    name: "hip flexor stretch",
    unit: "sec",
    areas: [HIP, QUADS],
  },
  {
    id: "303",
    category: MOBILITY,
    name: "seated glute stretch",
    unit: "sec",
    areas: [GLUTES, SPINAL_ERECTOR, OBLIQUES],
  },
  {
    id: "304",
    category: MOBILITY,
    name: "seated diagonal back stretch",
    unit: "sec",
    areas: [SPINAL_ERECTOR, HAMSTRINGS, CALVES],
  },
  {
    id: "305",
    category: MOBILITY,
    name: "wrist stretch",
    unit: "sec",
    areas: [FOREARMS],
  },
  {
    id: "306",
    category: MOBILITY,
    name: "seated glute stretch, leg backward",
    unit: "sec",
    areas: [GLUTES, SPINAL_ERECTOR, OBLIQUES],
  },
  {
    id: "307",
    category: MOBILITY,
    name: "quad stretch",
    unit: "sec",
    areas: [QUADS],
  },
  {
    id: "308",
    category: MOBILITY,
    name: "the frog stretch",
    unit: "sec",
    areas: [HIP, INNER_THIGH, SPINAL_ERECTOR],
  },
  {
    id: "309",
    category: MOBILITY,
    name: "half-split stretch",
    unit: "sec",
    areas: [OUTER_THIGH, HIP, GLUTES, LATS, SPINAL_ERECTOR],
  },
  {
    id: "310",
    category: MOBILITY,
    name: "seated forward back stretch",
    unit: "sec",
    areas: [SPINAL_ERECTOR, CALVES, HAMSTRINGS],
  },
  {
    id: "311",
    category: MOBILITY,
    name: "laying down stretch",
    unit: "sec",
    areas: [PECS, SPINAL_ERECTOR, LATS, OBLIQUES],
  },
  {
    id: "312",
    category: MOBILITY,
    name: "the cobra stretch",
    unit: "sec",
    areas: [SPINAL_ERECTOR, PECS, LATS],
  },
  {
    id: "313",
    category: MOBILITY,
    name: "the cross stretch",
    unit: "sec",
    areas: [SPINAL_ERECTOR, DELTS],
  },
  {
    id: "314",
    category: MOBILITY,
    name: "shoulder stretch from all four",
    unit: "sec",
    areas: [DELTS, OBLIQUES],
  },
  {
    id: "315",
    category: MOBILITY,
    name: "downward facing dog",
    unit: "sec",
    areas: [DELTS, HAMSTRINGS, CALVES, FOREARMS],
  },
  {
    id: "316",
    category: MOBILITY,
    name: "seated elephant shoulder stretch",
    unit: "sec",
    areas: [DELTS, LATS],
  },
  {
    id: "317",
    category: MOBILITY,
    name: "russian squat",
    unit: "sec",
    areas: [HIP, SPINAL_ERECTOR, HAMSTRINGS],
  },
  {
    id: "318",
    category: MOBILITY,
    name: "half-lotus",
    unit: "sec",
    areas: [FOREARMS, HIP, GLUTES],
  },
  {
    id: "319",
    category: MOBILITY,
    name: "backward roll",
    unit: "sec",
    areas: [ABS, OBLIQUES, SPINAL_ERECTOR],
  },
  {
    id: "320",
    category: MOBILITY,
    name: "lie down and breathe",
    unit: "sec",
    areas: [],
  },
];
